### PR TITLE
Improve README hierarchy, add detailed installation instructions

### PR DESCRIPTION
**Pull request by Scrumplex**
This PR improves the overall presentation of the README. It also adds a link to the unofficial AUR package provided by me.

**Summary**:

- Adjusted titles to match the hierarchy
- Added detailed installation instructions
- Added link to unofficial AUR package

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
See what you think of my change, I would prefer not having a subsection for Linux because if someone is looking for install instructions they will just scroll till they see the title for the platform they want and the "There are multiple ways to install ElectronPlayer on Linux." line is kinda useless. I am happy with the Arch repo being maintained by you for now but is it possible for it to be merged into the Travis so it is an official release and so it doesn't lag behind with updates. I also personally believe releases should be automatic and not done by a human (which I assume you are doing now). I can help you do this if you would like as I don't have a huge amount of knowledge about Arch and its package system. Thanks for your contribution.

**Comment by Scrumplex** [comment]
I do understand your changes there and I am completely fine with that.

I would need to look into Travis as I don't know how this could be set up.

How I would update the package manually:
1. Change the pkgver variable to the newest GitHub release
2. Update the sha512sum of the release archive (tar.gz)
3. Test if everything still works

For most releases this can be automated, but would need manual fixing, if something major changes. I don't think this is the first time, someone wants to automate AUR packages on GitHub. I will look into it. I think, that you can merge the PR as is, as it fulfills it's goal of improving the README.

**Comment by oscartbeaumont** [comment]
If you want just send me the bash commands used to do the release and I can set it up with Travis.

**Comment by oscartbeaumont** [comment]
The Arch conversation can be continued in #16, I am merging this PR.

**Pull request merged**
