### PR TITLE
Add SVG logos, add new loading screen, remove React dependency

### PR DESCRIPTION
**Pull request by Scrumplex**
This PR replaces the logos for YouTube, Twitch and Floatplane with SVG ones. **This breaks logos on older versions, as the file extensions have changed. Possibly adding the old ones back for backwards compatibility?** Furthermore it removes the React dependency from the frontend, as I could not see how to fully utilize it in this scope. The largest change is the new loading screen.

**Summary**
 - Remove React
 - Replace logos for SVG ones (breaks older versions)
 - Give user a way to completely style custom services
 - Add color attribute to services for loading screen
 - Add new screenshot

[Video of the new loading screen](https://youtu.be/t9B6FDr_g3U)

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
I like the change to svg logos as it was my laziness that lead to using pngs. I am still reviewing the move away from React. React was overkill, and I just used it because I am familiar with it, so I think it will be good.

**Comment by Scrumplex** [comment]
I assumed that :smile:

I think React could / should be considered again when adding in-app settings and customizations. I just didn't see the need in it's current state.

**Comment by oscartbeaumont** [comment]
That loader looks so amazing. Is it possible for it to be added to the menubar items?

**Comment by Scrumplex** [comment]
Yes it is. It was the plan initially, but for some reason the animation did not work correctly for some reason. I can look into it.

**Comment by oscartbeaumont** [comment]
If you can't get it working it is fine but worth a try since the loader looks so amazing!!!!

**Comment by Scrumplex** [comment]
Got it!

For some reason `requestAnimationFrame` does not work in this async context and runs instantly. I changed that to `setTimeout` with a delay of 1ms instead. A little hacky but it works.

**Comment by Scrumplex** [comment]
I want to clean something up before you merge.

**Comment by Scrumplex** [comment]
Okay I am done, I think. I'm glad that you like the animation. I had fun creating it!

**Comment by oscartbeaumont** [comment]
Upgrading now alerts the user to reset their configuration and gives them the ability to backup any changes they made, prior to it being reset. This updates the default services. Its really annoying I can't close issue #9 now cause it would have been much easier! Thanks for all your work on this project, I can't get over how awesome that loading animation is.

**Pull request merged**
