### PR TITLE
Remove mentions of AUR package from README.md

### PR DESCRIPTION
**Pull request by gardotd426**
For some reason (and with no explanation or warning given, the maintainer removed electronplayer from the AUR. There is now no way to install electronplayer on Arch except through Snap, AppImage, or by building from source.

### CODE REVIEW

**Comment by gardotd426** [comment]
Actually I went ahead and picked it up, so if you wanna just direct them to my github instead or something, or remove the mention of scrumplex. But yeah I'm maintaining the AUR package now.

**Comment by oscartbeaumont** [comment]
Do you want to replace the mention in the README to point to your repo before I merge this?

**Comment by oscartbeaumont** [comment]
Thanks for taking up the AUR!

**Comment by gardotd426** [comment]
Sure thing. Fixed.

**Comment by oscartbeaumont** [comment]
Thanks.

**Pull request merged**
