### PR TITLE
Scale SVG files instead of using CSS transforms

### PR DESCRIPTION
**Pull request by Scrumplex**
This PR scales the SVGs to similar sizes so we don't need to do that with CSS transforms, as these are a bit buggy with the loading animation.

**Summary**
 - Scale SVGs to similar sizes (around 200px wide and tall)
 - Speed up CSS transition a bit (from 0.3s to 0.2s)
 - Change wording on reset message
 - Add some explaining comment to code

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
This is going to need another config reset which sucks but I will add that tomorrow. This config update should be able to detect if a user changed their config and do a silent update if they didn't change anything thanks to the new schema added in the last release and hopefully I can make it automatically do this for future releases if the default config is changed.

**Comment by oscartbeaumont** [comment]
Is it possible for Youtube to be scaled a tad more? It still looks a bit smaller than the others.

**Comment by Scrumplex** [comment]
Scaling YouTube's logo would only be possible through CSS, though it would then be larger than the box it is in. As far as I can tell the loading animation looks buggy when there are any transformations on the img.
Imo it looks perfectly fine, despite it's shape.

**Comment by oscartbeaumont** [comment]
Ok cool, merging

**Comment by oscartbeaumont** [comment]
@Scrumplex How did you resize the logos as I would like to resize the Hulu and Amazon Prime Video logos which have recently been added to the repo and I can't work out how.

**Pull request merged**
